#!/usr/bin/env bash
#
# BotShop — one-command server bootstrap (Debian/Ubuntu VPS).
#
#   bash scripts/quickstart-vps.sh
#
# It will:
#   1. install Docker + the Compose plugin if they are missing
#   2. ask for your domain (or "none" to run internal-only)
#   3. generate strong secrets and write them to .env  (never overwrites an existing .env)
#   4. build and start the stack, then print the exact URLs and next steps
#
# Safe to re-run: everything is idempotent, and an existing .env is left untouched.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

say()  { printf '\n\033[1;36m%s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m%s\033[0m\n' "$*"; }
die()  { printf '\033[1;31m%s\033[0m\n' "$*" >&2; exit 1; }

need_sudo() {
  if [ "$(id -u)" -eq 0 ]; then echo ""; elif command -v sudo >/dev/null 2>&1; then echo "sudo"; else die "Run as root or install sudo."; fi
}

random_hex() {
  local bytes="$1"
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex "$bytes"
  elif command -v python3 >/dev/null 2>&1; then python3 -c "import secrets,sys;print(secrets.token_hex(int(sys.argv[1])))" "$bytes"
  else head -c "$bytes" /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

# ---------------------------------------------------------------- 1. docker
say "Step 1/4 · Checking Docker"
if ! command -v docker >/dev/null 2>&1; then
  SUDO="$(need_sudo)"
  warn "Docker is not installed — installing it (docker.io + compose plugin)."
  command -v apt-get >/dev/null 2>&1 || die "Automatic install supports Debian/Ubuntu only. Install Docker manually, then re-run."
  $SUDO apt-get update -qq
  $SUDO apt-get install -y -qq docker.io docker-compose-plugin curl ca-certificates
  $SUDO systemctl enable --now docker
else
  echo "  docker: $(docker --version)"
fi
if ! docker compose version >/dev/null 2>&1; then
  die "The 'docker compose' plugin is missing. Install docker-compose-plugin (or use docker-compose v2) and re-run."
fi
echo "  compose: $(docker compose version --short 2>/dev/null || echo ok)"

# ---------------------------------------------------------------- 2. domain
say "Step 2/4 · Public address"
echo "Telegram needs HTTPS to deliver messages (webhooks). Two options:"
echo "  • you have a domain (recommended):  it must already point at this server's IP"
echo "  • you do not:                        answer 'none' — we will use polling mode instead"
printf 'Domain (e.g. shop.example.com) or "none": '
read -r DOMAIN
DOMAIN="$(printf '%s' "$DOMAIN" | tr '[:upper:]' '[:lower:]' | tr -d ' ')"

USE_EDGE=false
if [ "$DOMAIN" = "none" ] || [ -z "$DOMAIN" ]; then
  PUBLIC_BASE_URL="http://localhost:3000"
  POLLING="true"
  warn "No domain: the stack will run on http://<server-ip>:3000 and bots must use POLLING mode."
  echo "  (Polling needs no TLS, which is why it is the fallback.)"
else
  PUBLIC_BASE_URL="https://${DOMAIN}"
  POLLING="false"
  USE_EDGE=true
  echo "  Will serve https://${DOMAIN} with automatic TLS certificates (Caddy)."
  echo "  Reminder: create a DNS A record -> this server's public IP before continuing."
  printf "Press Enter when the DNS record exists, or Ctrl+C to stop. "
  read -r _
fi

# ---------------------------------------------------------------- 3. secrets
say "Step 3/4 · Secrets and configuration"
if [ -f .env ]; then
  echo "  .env already exists — leaving it exactly as it is."
else
  POSTGRES_PASSWORD="$(random_hex 24)"
  APP_DB_PASSWORD="$(random_hex 24)"
  ENCRYPTION_KEY="$(random_hex 32)"
  APP_PORT="${APP_PORT:-3000}"

  # Never write a weak or empty secret: if no random source worked, stop and say what to install.
  for pair in "POSTGRES_PASSWORD:$POSTGRES_PASSWORD" "APP_DB_PASSWORD:$APP_DB_PASSWORD" "ENCRYPTION_KEY:$ENCRYPTION_KEY"; do
    name="${pair%%:*}"; value="${pair#*:}"
    if [ "${#value}" -lt 32 ]; then
      die "Could not generate a secure random value for ${name} on this server.\nInstall a random source (apt-get install -y openssl) and run this script again."
    fi
  done

  cat > .env <<EOF
# Generated by scripts/quickstart-vps.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# KEEP THIS FILE PRIVATE. It contains the key that decrypts merchant bot tokens.
NODE_ENV=production
APP_PORT=${APP_PORT}
PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
PUBLIC_DOMAIN=${DOMAIN}

POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=botshop
APP_DB_PASSWORD=${APP_DB_PASSWORD}

ENCRYPTION_KEYS=k1:${ENCRYPTION_KEY}
ENCRYPTION_ACTIVE_KEY_ID=k1

TELEGRAM_MODE=live
TELEGRAM_POLLING=${POLLING}
TELEGRAM_WEBHOOK_ENABLED=true

SESSION_TTL_HOURS=336
LOG_LEVEL=info
RUN_MIGRATIONS=true
SEED_ON_BOOT=false
EOF
  chmod 600 .env
  echo "  Wrote .env (permissions 600) with freshly generated database + encryption secrets."
  echo "  Back this file up somewhere safe — losing ENCRYPTION_KEYS means losing connected bot tokens."
fi

# ---------------------------------------------------------------- 4. start
say "Step 4/4 · Building and starting (first build takes a few minutes)"
if [ "$USE_EDGE" = true ]; then
  docker compose --profile edge up -d --build
else
  docker compose up -d --build
fi

echo
echo "Waiting for the API to answer /healthz …"
for _ in $(seq 1 60); do
  if curl -fsS http://127.0.0.1:"${APP_PORT:-3000}"/healthz >/dev/null 2>&1; then
    HEALTHY=true; break
  fi
  sleep 2
done

say "Done — here is where everything lives"
cat <<EOF
  Panel              ${PUBLIC_BASE_URL}          (or http://<server-ip>:${APP_PORT:-3000} if you chose "none")
  Health check       ${PUBLIC_BASE_URL%/}/healthz
  Project files      ${ROOT}
  Secrets            ${ROOT}/.env                (chmod 600 — back it up, never commit it)
  Database data      Docker volume "botshop_db-data"   (persists across restarts)
  Backups            put dumps in ${ROOT}/backups/     (see docs/DEPLOYMENT.md)

Next steps in the browser
  1. Open the panel and click "Create a workspace" (there are no default accounts in production).
  2. Setup wizard step 1–3: business name, currency, languages, policies, staff chat id.
  3. Step 4: create a bot with @BotFather, paste the token, choose $([ "$POLLING" = true ] && echo "Polling" || echo "Webhook").$([ "$POLLING" = true ] && echo "  (no domain/TLS needed)" || echo "")
  4. Step 5: preview the screens. Step 6: launch.
  5. In Telegram, send /start to your bot — you should see the language picker, then the menu.

Day-2 commands
  docker compose logs -f app          # live logs (startup, errors, webhook traffic)
  docker compose ps                   # what is running
  docker compose restart app          # after editing .env
  docker compose down                 # stop (data is kept)
  docker compose down -v              # stop AND delete the database — destructive
EOF

if [ "${HEALTHY:-false}" != true ]; then
  warn "The API is not answering yet. Check 'docker compose logs app' — common causes are a busy port or a database password mismatch."
fi
